# Generated by Django 5.0.1 on 2024-02-26 19:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('telemetria', '0003_mergedtelemetricacctionid8'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='MergedTelemetricAcctionId8',
            new_name='MergedTelemetricActionId8',
        ),
    ]
