# Generated by Django 5.0.1 on 2024-02-27 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telemetria', '0007_alter_mergedtelemetricactionid8_timestamp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='telemetria',
            name='timestamp',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
