# Generated by Django 5.0.1 on 2024-03-01 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telemetria', '0008_alter_telemetria_timestamp'),
    ]

    operations = [
        migrations.CreateModel(
            name='MergedTelemetricOTT',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('actionId', models.IntegerField(blank=True, null=True)),
                ('actionKey', models.CharField(blank=True, max_length=20, null=True)),
                ('anonymized', models.BooleanField(blank=True, null=True)),
                ('data', models.CharField(blank=True, max_length=200)),
                ('dataDuration', models.IntegerField(blank=True, null=True)),
                ('dataId', models.IntegerField(blank=True, null=True)),
                ('dataName', models.CharField(blank=True, max_length=200, null=True)),
                ('dataNetId', models.IntegerField(blank=True, null=True)),
                ('dataPrice', models.IntegerField(blank=True, null=True)),
                ('dataSeviceId', models.IntegerField(blank=True, null=True)),
                ('dataTsId', models.IntegerField(blank=True, null=True)),
                ('date', models.IntegerField(blank=True, null=True)),
                ('deviceId', models.IntegerField(blank=True, null=True)),
                ('ip', models.GenericIPAddressField(blank=True, null=True)),
                ('ipId', models.IntegerField(blank=True, null=True)),
                ('manual', models.BooleanField(blank=True, null=True)),
                ('profileId', models.IntegerField(blank=True, null=True)),
                ('reaonId', models.IntegerField(blank=True, null=True)),
                ('reasonKey', models.CharField(blank=True, max_length=20, null=True)),
                ('recordId', models.IntegerField(blank=True, null=True)),
                ('smartcardId', models.CharField(max_length=50, null=True)),
                ('subscriberCode', models.CharField(max_length=50, null=True)),
                ('timestamp', models.DateTimeField(blank=True, null=True)),
                ('dataDate', models.DateField(blank=True, null=True)),
                ('timeDate', models.IntegerField(blank=True, null=True)),
                ('whoisCountry', models.CharField(blank=True, max_length=20, null=True)),
                ('whoisIsp', models.CharField(blank=True, max_length=20, null=True)),
            ],
        ),
        migrations.RenameModel(
            old_name='MergedTelemetricActionId8',
            new_name='MergedTelemetricDVB',
        ),
    ]
