# Generated by Django 5.0.1 on 2024-03-15 11:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('telemetria', '0009_mergedtelemetricott_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='telemetria',
            name='dataDate',
        ),
        migrations.RemoveField(
            model_name='telemetria',
            name='timeDate',
        ),
    ]
