# Generated by Django 5.0.1 on 2024-03-15 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telemetria', '0010_remove_telemetria_datadate_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='telemetria',
            name='data',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
