# Generated by Django 5.0.3 on 2024-03-13 16:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('telemetria', '0010_mergedtelemetriccatchup'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='telemetria',
            name='dataDate',
        ),
        migrations.RemoveField(
            model_name='telemetria',
            name='timeDate',
        ),
    ]
