# Generated by Django 5.0.1 on 2024-03-18 10:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('telemetria', '0011_remove_telemetria_datadate_and_more'),
        ('telemetria', '0012_telemetria_datadate_telemetria_timedate'),
    ]

    operations = [
    ]
