# Generated by Django 5.0.1 on 2024-03-18 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telemetria', '0013_merge_20240318_1038'),
    ]

    operations = [
        migrations.AddField(
            model_name='telemetria',
            name='dataDate',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='telemetria',
            name='timeDate',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
