# Generated by Django 5.0.3 on 2024-04-03 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telemetria', '0015_alter_mergedtelemetriccatchup_data_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='telemetria',
            name='recordId',
            field=models.IntegerField(blank=True, null=True, unique=True),
        ),
    ]
