# Generated by Django 5.0.1 on 2024-04-29 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telemetria', '0017_mergedtelemetricendvod_mergedtelemetricstopcatchup_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mergedtelemetricdvb',
            name='recordId',
            field=models.IntegerField(blank=True, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='mergedtelemetricendcatchup',
            name='recordId',
            field=models.IntegerField(blank=True, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='mergedtelemetricendvod',
            name='recordId',
            field=models.IntegerField(blank=True, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='mergedtelemetricott',
            name='recordId',
            field=models.IntegerField(blank=True, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='mergedtelemetricstopcatchup',
            name='recordId',
            field=models.IntegerField(blank=True, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='mergedtelemetricstopvod',
            name='recordId',
            field=models.IntegerField(blank=True, null=True, unique=True),
        ),
    ]
